all: HelloWorld assignment

HelloWorld: HelloWorld.cpp
	g++ HelloWorld.cpp -o HelloWorld -l OpenCL

assignment: assignment.cpp
	g++ assignment.cpp -o assignment -l OpenCL

clean:
	rm -f HelloWorld assignment
